### ISSUE TITLE
How to specify GPU for model training？

### ISSUE THREAD

**Issue by yz-hust** [creatis-myriad/ASCENT#159]
How can I specify a specific GPU among multiple GPUs to train the model? There is no relevant description in the documentation. Looking forward to your reply!

**Comment by HangJung97** [comment]
Hey,

`ascent_train ... "trainer.devices=[0]"` should do the trick. This uses the GPU 0 for training.

Best,
HJ

**Comment by yz-hust** [comment]
I tried for quite a while yesterday with the parameter "trainer.devices=1" and it never worked. With your guidance, I have successfully resolved this issue. I am grateful for your help.



---- Replied Message ----
| From | Hang Jung ***@***.***> |
| Date | 04/19/2024 15:00 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [creatis-myriad/ASCENT] How to specify GPU for model training？ (Issue #159) |

Hey,

ascent_train ... "trainer.devices=[0]" should do the trick. This uses the GPU 0 for training.

Best,
HJ

**Comment by HangJung97** [comment]
I'm glad that your problem has been solved! I'll close this issue as resolved.

**Comment by yz-hust** [comment]
ok



---- Replied Message ----
| From | Hang Jung ***@***.***> |
| Date | 04/19/2024 15:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [creatis-myriad/ASCENT] How to specify GPU for model training？ (Issue #159) |

I'm glad that your problem has been solved! I'll close this issue as resolved.
