### ISSUE TITLE
about the VFM

### ISSUE THREAD

**Issue by whucsu** [creatis-myriad/ASCENT#166]
thanks for sharing the code.
when will the VFM implementation be added to the code ?
best wishes~

**Comment by HangJung97** [comment]
Hi,

The VFM codes will be released shortly, but not in this repository. Please stay tuned!

Best,
Hang Jung

**Comment by whucsu** [comment]
best wishes. please share me the new repository when released.

**Comment by HangJung97** [comment]
Sure. I will close this issue for now.

**Comment by whucsu** [comment]
> Hi,
> 
> The VFM codes will be released shortly, but not in this repository. Please stay tuned!
> 
> Best, Hang Jung

is the VFM code released ? thanks
