### ISSUE TITLE
Question about the project

### ISSUE THREAD

**Issue by amine0110** [creatis-myriad/ASCENT#167]
Hello

Thank you very much for the project.

I have a question concerning the method you are using. Can you please specify what is the difference between using your project or if we use nnUNet directly?

I see that you are using additional libraries such as MONAI... What is the role of these libraries?

Also one final question, when I used the original nnUNet, the inference time is very slow, do you think that your project is faster than the classical nnUNet?

Thank you in advance for your response
Best wishes

**Comment by HangJung97** [comment]
Hi,

This is actually the reimplemented version of nnU-Net with Lightning, Monai, and Hydra. The main motivation of developing this repository is to integrate nnU-Net more easily in my different research projects. I did not reimplement the whole functionalities of nnU-Net, but only the ones required for my projects. The role of Monai is for managing the data loading and transforms. My code should produce similar segmentation performances as the nnU-Net V1 (I never compare it with the V2). And regarding the inference time, my code will not be faster than the original nnU-Net. 

Best,
Hang Jung

**Comment by amine0110** [comment]
Thank you for your response
